#!/usr/bin/env python3
"""Utilities for building NeurIPS paper artifacts from canonical repo outputs."""

from __future__ import annotations

import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, pstdev
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUTS_ROOT = REPO_ROOT / "outputs"
PAPER_TABLE_DIR = OUTPUTS_ROOT / "paper_tables"
PAPER_PLOT_DIR = OUTPUTS_ROOT / "paper_plot_data"

IMPORTED_ROOT = OUTPUTS_ROOT / "imported_methodology_frontier_eval"
FULL_BUNDLE_ROOT = OUTPUTS_ROOT / "full_method_comparison_bundle"

REQUIRED_IMPORTED_FILES = {
    "method_metrics.csv",
    "oracle_gap_summary.csv",
    "matched_comparison_summary.csv",
    "budget_frontier_summary.csv",
    "signal_slice_summary.csv",
    "summary.json",
}
REQUIRED_FULL_BUNDLE_FILES = {
    "manifest.json",
    "per_seed_method_metrics.csv",
    "per_method_metrics.csv",
    "per_example_outcomes.csv",
    "per_budget_ranking.csv",
    "per_dataset_ranking.csv",
}

FIXED_METHODS = [
    "reasoning_greedy",
    "self_consistency_3",
    "reasoning_beam2",
    "verifier_guided_search",
    "program_of_thought",
]

ADAPTIVE_HEURISTIC_METHODS = [
    "adaptive_budget_guarded",
    "adaptive_min_expand_2",
    "adaptive_min_expand_1",
    "adaptive_min_expand_0",
]

LEARNED_POLICY_CANDIDATES = [
    "adaptive_bt_pairwise_reliability",
    "adaptive_bt_pairwise",
]


def _fail(msg: str) -> None:
    raise FileNotFoundError(msg)


def _latest_run_dir(root: Path, required_files: set[str]) -> Path:
    if not root.exists():
        _fail(f"Missing canonical root directory: {root}")
    run_dirs = sorted([p for p in root.iterdir() if p.is_dir()])
    if not run_dirs:
        _fail(f"No run directories found under {root}")
    valid = []
    for run in run_dirs:
        missing = [f for f in required_files if not (run / f).exists()]
        if not missing:
            valid.append(run)
    if not valid:
        _fail(f"No valid run directory under {root} contains required files: {sorted(required_files)}")
    return valid[-1]


def canonical_paths() -> dict[str, Path]:
    imported_run = _latest_run_dir(IMPORTED_ROOT, REQUIRED_IMPORTED_FILES)
    full_bundle_run = _latest_run_dir(FULL_BUNDLE_ROOT, REQUIRED_FULL_BUNDLE_FILES)
    return {
        "imported_run": imported_run,
        "full_bundle_run": full_bundle_run,
    }


def ensure_output_dirs() -> None:
    PAPER_TABLE_DIR.mkdir(parents=True, exist_ok=True)
    PAPER_PLOT_DIR.mkdir(parents=True, exist_ok=True)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_tex_table(path: Path, headers: list[str], rows: list[list[str]], caption: str, label: str) -> None:
    lines = [
        "% Auto-generated by scripts/paper.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{" + "l" * len(headers) + "}",
        "\\toprule",
        " & ".join(headers) + " \\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(" & ".join(r) + " \\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def as_float(x: Any, default: float = 0.0) -> float:
    try:
        return float(x)
    except Exception:
        return default


def fmt(x: float, ndigits: int = 4) -> str:
    return f"{x:.{ndigits}f}"


@dataclass
class Inputs:
    imported_run: Path
    full_bundle_run: Path



def load_inputs() -> Inputs:
    paths = canonical_paths()
    return Inputs(imported_run=paths["imported_run"], full_bundle_run=paths["full_bundle_run"])


def budget_buckets(budgets: list[int]) -> dict[int, str]:
    uniq = sorted(set(budgets))
    if not uniq:
        return {}
    if len(uniq) == 1:
        return {uniq[0]: "single"}
    if len(uniq) == 2:
        return {uniq[0]: "low", uniq[1]: "high"}
    mid = uniq[len(uniq) // 2]
    return {uniq[0]: "low", mid: "medium", uniq[-1]: "high"}


def allocation_diversity_from_oracle(
    per_example_rows: list[dict[str, str]], method_pool: list[str]
) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = {}
    for r in per_example_rows:
        key = (r["dataset"], r["seed"], r["budget"])
        grouped.setdefault(key, []).append(r)

    out: list[dict[str, Any]] = []
    for (dataset, seed, budget), rows in sorted(grouped.items()):
        by_ex: dict[str, list[dict[str, str]]] = {}
        for r in rows:
            if r["method"] in method_pool:
                by_ex.setdefault(r["example_id"], []).append(r)
        if not by_ex:
            continue

        method_share = {m: 0.0 for m in method_pool}
        oracle_hits = 0
        per_method_correct = {m: 0 for m in method_pool}

        for ex_rows in by_ex.values():
            correct = [r for r in ex_rows if str(r.get("is_correct", "")).lower() in {"1", "true"}]
            if correct:
                oracle_hits += 1
                winners = [r["method"] for r in correct]
            else:
                min_act = min(as_float(r.get("actions_used", 9999.0)) for r in ex_rows)
                winners = [r["method"] for r in ex_rows if as_float(r.get("actions_used", 9999.0)) == min_act]
            frac = 1.0 / max(1, len(winners))
            for m in winners:
                method_share[m] += frac

            for m in method_pool:
                mr = next((r for r in ex_rows if r["method"] == m), None)
                if mr and str(mr.get("is_correct", "")).lower() in {"1", "true"}:
                    per_method_correct[m] += 1

        n_ex = len(by_ex)
        probs = [method_share[m] / n_ex for m in method_pool]
        entropy = -sum(p * math.log(p) for p in probs if p > 0)
        max_entropy = math.log(len(method_pool)) if len(method_pool) > 1 else 1.0
        normalized_entropy = (entropy / max_entropy) if max_entropy > 0 else 0.0
        max_share = max(probs) if probs else 0.0
        n_active = sum(1 for p in probs if p > 1e-12)

        out.append(
            {
                "dataset": dataset,
                "seed": int(seed),
                "budget": int(budget),
                "n_examples": n_ex,
                "method_pool_size": len(method_pool),
                "allocation_entropy": normalized_entropy,
                "max_family_share": max_share,
                "n_active_families": n_active,
                "family_coverage": n_active / max(1, len(method_pool)),
                "oracle_frontier_accuracy": oracle_hits / max(1, n_ex),
                "best_single_family_reference_accuracy": max((c / max(1, n_ex) for c in per_method_correct.values()), default=0.0),
            }
        )
    return out


def mean_std(values: list[float]) -> tuple[float, float]:
    if not values:
        return (0.0, 0.0)
    if len(values) == 1:
        return (values[0], 0.0)
    return (mean(values), pstdev(values))
